# Generated by Django 4.2 on 2024-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.TextField()),
            ],
        ),
    ]
